### PR TITLE
Send character to server

### PR DESCRIPTION
**Pull request by Apexal**
This PR introduces the functionality to send a character to the Wrathserver cache and display the returned character ID!

### CODE REVIEW

**Review by talios0 — CHANGES_REQUESTED** [review]
Nice!

Works well and the feedback message is easy to understand. Feel free to ignore this, but the user can re-send the same character to the server and will receive a new code each time. Something like this (along with trying to send too many characters in general) might be a concern for if the server needed to handle hundreds+ of character requests.

**Comment by Apexal** [comment]
> Nice!
> 
> Works well and the feedback message is easy to understand. Feel free to ignore this, but the user can re-send the same character to the server and will receive a new code each time. Something like this (along with trying to send too many characters in general) might be a concern for if the server needed to handle hundreds+ of character requests.

Good call. I think the best solution here would be to include a timestamp along with `id` on the server side that stores the time that the id expires. Then, the frontend can determine when to display the same ID versus request a new one.

**Comment by Apexal** [comment]
Oops, accidentally rerequested review from the GitHub mobile app. I'll make those changes discussed above first.

**Comment by Apexal** [comment]
Actually, now that I think about it, the current functionality makes characters in the cache immutable. If they change (or don't) they get a different temporary character ID when sent to the server. This saves us from having to write any "update" functionality on the server as we can just modify the character in Wrathspriter and post it to the server as a new character.

**Pull request merged**
